### ISSUE TITLE
Base64 for macaroons/certs

### ISSUE THREAD

**Issue by andrerfneves** [apotdevin/thunderhub#123]
**Is your feature request related to a problem? Please describe.**
Right now it seems I need to run Thunderhub on the same server that has access to the macaroon and cert files. I'd like to split the two so Thunderhub runs under a private aws subnet and only has specific access restricted. But the macaroon and cert files are not available in such a server.

**Describe the solution you'd like**
I'd love to be able to be able to pass `base64` strings for the macaroon and cert files.

**Describe alternatives you've considered**
I can always SCP the macaroon and cert across internal servers but would love to not need to do that and pass base64 strings across.

This would allow for better separation of concerns between internal services and better security around the 10009 API port access.

**Comment by apotdevin** [comment]
Hey! I believe [this is the section](https://github.com/apotdevin/thunderhub#server-accounts) you are looking for

In the server accounts yaml file you can also specify directly the macaroon and certificate in either HEX or Base64 format.

This is an example of how you would want this file:

```yaml
masterPassword: 'password' # Default password unless defined in account
accounts:
  - name: 'Account 1'
    serverUrl: 'url:port'
    macaroon: '0201056...' # HEX or Base64 encoded macaroon
    certificate: '0202045c...' # HEX or Base64 encoded certificate
```

Let me know if this would work for you!
