### ISSUE TITLE
Password not set to environment variable

### ISSUE THREAD

**Issue by krtk6160** [apotdevin/thunderhub#259]
**Describe the problem/bug**
Setting password as an environment variable does not work. The account sections inside the thunderhub.yaml file looks like this:
```
accounts:
  - name: 'Primary'
    serverUrl: 'lnd:10009'
    macaroon: '{YML_ENV_1}'
    certificate: '{YML_ENV_2}'
    password: '{YML_ENV_3}'
```

While the macaroon and certificate are correctly assigned the value from the environment variables, for the password, the string `{YML_ENV_3}` is set as the password. I have verified that inside the docker container, all three environment variables are correctly set.

**Your environment**
* Version of ThunderHub: v0.12.7
* Deployment method: Official docker image
* Other relevant environment details: Minikube v1.19.0

**To Reproduce**
1. Configure thunderhub.yaml file to pick up password from an environment variable.
2. Mount the required environment variables
3. Try to login using the value of the environment variable
4. Get incorrect password error
5. Try to login with the password as `{YML_ENV_X}` where X ranges from 1 to 4, and is the value that was set in thunderhub.yaml.
6. Login succeeds

**Expected behavior**
Environment variable's value should be set as password

**Actual behavior**
Environment variable's name itself is being set as password
