### ISSUE TITLE
TypeError: Object.fromEntries is not a function

### ISSUE THREAD

**Issue by rock217** [apotdevin/thunderhub#271]
**Describe the problem/bug**
Initial page request crash

**Your environment**
* Version of ThunderHub: commit 4399a046c6286eb6e97a272f7225de6f7a5a3684 (HEAD -> master, tag: v0.12.18, origin/master, origin/HEAD)
* Deployment method: npm
* Other relevant environment details:
```
root@lnd1:~/thunderhub# node -v
v10.24.0
root@lnd1:~/thunderhub# npm -v
5.8.0
```

**To Reproduce**
1. `npm start -- -p 3000`
2. `localhost:3000`

**Expected behavior**
See a login page or the dashboard

**Actual behavior**
internal server error

**Screenshots/Links**
```
TypeError: Object.fromEntries is not a function
    at resolveEnvVarsInAccount (/root/thunderhub/.next/server/pages/_app.js:2680:27)
    at getParsedAccount (/root/thunderhub/.next/server/pages/_app.js:2874:27)
    at accounts.map (/root/thunderhub/.next/server/pages/_app.js:2960:59)
    at Array.map (<anonymous>)
    at getAccountsFromYaml (/root/thunderhub/.next/server/pages/_app.js:2960:35)
    at getAccounts (/root/thunderhub/.next/server/pages/_app.js:2871:10)
    at Module.fbJj (/root/thunderhub/.next/server/pages/_app.js:5653:109)
    at __webpack_require__ (/root/thunderhub/.next/server/pages/_app.js:23:31)
    at createIsomorphLink (/root/thunderhub/.next/server/pages/_app.js:1440:9)
    at createApolloClient (/root/thunderhub/.next/server/pages/_app.js:1453:11)
```

**Additional context**
```
.env.local
ACCOUNT_CONFIG_PATH='/root/thunderhub/config.yaml'
```
```
config.yaml
masterPassword: xxxx-autohashed
defaultNetwork: 'mainnet'
accounts:
  - name: 'xxxx'
    serverUrl: '127.0.0.1:9735'
    lndDir: '/root/.lnd'
    macaroonPath: '/root/.lnd/data/chain/bitcoin/mainnet/admin.macaroon'
    certificatePath: '/root/.lnd/tls.cert'
    password: xxxx-autohashed
```
