### ISSUE TITLE
Issues during installation - cannot find macaroon or cert

### ISSUE THREAD

**Issue by bensig** [apotdevin/thunderhub#290]
**Describe the problem/bug**

Pointed .env SSO to the LND directory - files are there and permissions appear to be ok, but THUB cannot find them

 - logs report:
2021-07-01 19:24:50 error [THUB]: No admin.macaroon file found at path: <lndpath>/data/chain/bitcoin/mainnet/
2021-07-01 19:24:50 error [THUB]: No file found at path: <lndpath>/tls.cert

**Your environment**
* Version of ThunderHub: 0.12.20
* Deployment method: git clone // npm
* Other relevant environment details: node v14.15.5 on Ubuntu 20.04.2 LTS

**To Reproduce**
1. install on Ubuntu 20.04.2 LTS following GH instructions: npm install && npm run build && npm start -- -p 4000
2. add lnd paths to .env SSO section

**Expected behavior**
Expected to find files that exist

**Actual behavior**
THUB reports that files do not exist

**Comment by bensig** [comment]
Contents of .env
```
# -----------
# SSO Account Configs
# -----------
SSO_SERVER_URL = '127.0.0.1:10009'; # i.e. '127.0.0.1:10009'
SSO_CERT_PATH = '<lndpath>/tls.cert'; # i.e. '\lnd\alice\tls.cert'
SSO_MACAROON_PATH = '<lndpath>/data/chain/bitcoin/mainnet/'; # i.e. '\lnd\alice\data\chain\bitcoin\regtest\'
DANGEROUS_NO_SSO_AUTH = 'true' # Default: false
```

**Comment by apotdevin** [comment]
Why do you add `<lndpath>`? Try specifying the complete path

**Comment by bensig** [comment]
I don't actually add that to my config. 

I switched to a .env.local which looks like this
```
ACCOUNT_CONFIG_PATH = '/home/username/src/thunderhub/thubConfig.yaml'; # i.e. '/data/thubConfig.yaml'
LOG_LEVEL = 'error' | 'warn' | 'info' | 'http' | 'verbose' | 'debug' | 'silly' # Default: 'info'
THEME = 'dark' | 'light' | 'night' # Default: 'dark'
CURRENCY = 'sat' | 'btc' | 'fiat' # Default: 'sat'
FETCH_PRICES = true | false # Default: true
FETCH_FEES = true | false # Default: true
DISABLE_LINKS = true | false # Default: false
DISABLE_LNMARKETS = true | false # Default: false
NO_VERSION_CHECK = true | false # Default: false
```

thubConfig.yaml
```
masterPassword: 'mypass' # Default password unless defined in account
accounts:
  - name: 'username'
    serverUrl: '127.0.0.1:10009'
    lndDir: '/home/username/.lnd/'
    macaroonPath: '/home/username/.lnd/data/chain/bitcoin/mainnet/admin.macaroon'
    certificatePath: '/home/username/.lnd/tls.cert'
```
Then I am starting with `npm start -- -p 4000`

When I go to localhost:4000 I am getting this error
![image](https://user-images.githubusercontent.com/1872138/124537262-901dfb80-dde7-11eb-8f6c-eb0bfd019625.png)
