### ISSUE TITLE
Unable to start thunderhub v0.13.14 with docker-compose

### ISSUE THREAD

**Issue by microlancer** [apotdevin/thunderhub#469]
**Describe the problem/bug**
I was using thunderhub v0.12.31 and it was running fine. But I saw there's a new version so I updated my docker-compose:

```
version: '3'
services:
  thunderhub:
    image: apotdevin/thunderhub:v0.13.14
    restart: unless-stopped
    network_mode: host
    stop_signal: SIGKILL
    environment:
      # BASE_PATH: '/thub'
      # COOKIE_PATH: '/data/.cookie'
      # SSO_SERVER_URL: 'lnd_bitcoin:10009'
      # SSO_MACAROON_PATH: '/etc/lnd'
      # SSO_CERT_PATH: '/etc/lnd/tls.cert'
      # NO_CLIENT_ACCOUNTS: 'true'
      ACCOUNT_CONFIG_PATH: '/data/thubConfig.yaml'
      LOG_LEVEL: debug
    volumes:
      - ./data:/data
    ports:
      - '3000:3000'
    expose:
      - '3000'
    command: ['npm', 'run', 'start']
~                                     
```

I only changed the version number. Then I tried to start it, but I got an error.

```
$ docker-compose up
Pulling thunderhub (apotdevin/thunderhub:v0.13.14)...
v0.13.14: Pulling from apotdevin/thunderhub
2408cc74d12b: Already exists
5b80453a567d: Extracting [=================================================> ]  35.32MB/35.68MB
3420de6432e1: Download complete
5b80453a567d: Pull complete
3420de6432e1: Pull complete
65b549a28248: Pull complete
ef4a3c8855b2: Pull complete
6a9e44f3eb0e: Pull complete
dd6432d73969: Pull complete
f9c8b05b8489: Pull complete
3c665eb34651: Pull complete
d5542bf397a1: Pull complete
6a682dc50a0e: Pull complete
Digest: sha256:6ee592a8335ec203f9c7056ddd22f286f8135b5888005d84db70787a91e3e72f
Status: Downloaded newer image for apotdevin/thunderhub:v0.13.14
Recreating example_thunderhub_1 ... done
Attaching to example_thunderhub_1
thunderhub_1  | 
thunderhub_1  | > thunderhub@0.13.14 start
thunderhub_1  | > cross-env NODE_ENV=production nest start
thunderhub_1  | 
thunderhub_1  | node:events:505
thunderhub_1  |       throw er; // Unhandled 'error' event
thunderhub_1  |       ^
thunderhub_1  | 
thunderhub_1  | Error: spawn nest ENOENT
thunderhub_1  |     at Process.ChildProcess._handle.onexit (node:internal/child_process:283:19)
thunderhub_1  |     at onErrorNT (node:internal/child_process:478:16)
thunderhub_1  |     at processTicksAndRejections (node:internal/process/task_queues:83:21)
thunderhub_1  | Emitted 'error' event on ChildProcess instance at:
thunderhub_1  |     at Process.ChildProcess._handle.onexit (node:internal/child_process:289:12)
thunderhub_1  |     at onErrorNT (node:internal/child_process:478:16)
thunderhub_1  |     at processTicksAndRejections (node:internal/process/task_queues:83:21) {
thunderhub_1  |   errno: -2,
thunderhub_1  |   code: 'ENOENT',
thunderhub_1  |   syscall: 'spawn nest',
thunderhub_1  |   path: 'nest',
thunderhub_1  |   spawnargs: [ 'start' ]
thunderhub_1  | }
thunderhub_1  | npm notice 
thunderhub_1  | npm notice New minor version of npm available! 8.11.0 -> 8.14.0
thunderhub_1  | npm notice Changelog: <https://github.com/npm/cli/releases/tag/v8.14.0>
thunderhub_1  | npm notice Run `npm install -g npm@8.14.0` to update!
thunderhub_1  | npm notice 
example_thunderhub_1 exited with code 1
```

Any ideas what is causing this error?
