### ISSUE TITLE
Persistent message "To start you must create an account on your server"

### ISSUE THREAD

**Issue by smartm0use** [apotdevin/thunderhub#513]
As described in the [documentation](https://docs.thunderhub.io/setup/#server-accounts) I created and `.env` file and a `thubConfig.yaml` file in `thunderhub` folder.

Here is the content of thubConfig.yaml:

```
masterPassword: "password" # Default password unless defined in account
defaultNetwork: "mainnet"
accounts:
  - name: "<my_account_name>"
    serverUrl: "<my_address>.onion:50001"
    password: "test"
    lndDir: "."
  - name: "Account 2"
    serverUrl: "url:port"
    macaroonPath: "/path/to/admin.macaroon"
    certificatePath: "/path/to/tls.cert"
    # password: Leave without password and it will use the master password
  - name: "Account 3"
    serverUrl: "url:port"
    macaroon: "0201056..." # HEX or Base64 encoded macaroon
    certificate: "0202045c..." # HEX or Base64 encoded certificate
    password: "password for account 3"
```

In the `.env` file I linked the yaml file adding this line:

```
ACCOUNT_CONFIG_PATH = '<my-home>/thunderhub/thubConfig.yaml';
```

But when I run thunderhub and go to localhost:3000 the page still tells me "To start you must create an account on your server".

What am I doing wrong?

Environment: ThunderHub 0.13.18 on Ubuntu 22.04
