### ISSUE TITLE
Setup instructions are not clear.

### ISSUE THREAD

**Issue by DavinciCodes15** [apotdevin/thunderhub#59]
Can you provide real examples of the paths ports on a standard install of Lnd and bitcoin.

For example 
Whats this
    serverUrl: 'http://127.0.0.1:8080'
the RPC the 10009 port the 9735?

whats this?
masterPassword: 'password' # Default password unless defined in account

Is this correct?
SSO_CERT_PATH='/home/username/.lnd/tls.cert'
SSO_MACAROON_PATH='/home/username/.lnd/data/chain/bitcoin/mainnet/'
ACCOUNT_CONFIG_PATH='/home/username/thunderhub/thubConfig.yaml'

Also, where is the log so I can see if I did it all correctly?

Right now I enter 
http://remotecomputer:3000
and I get a flash of the screen and blank.

**Comment by apotdevin** [comment]
Hi! Sorry for that. To setup an account on the server these are the steps you need:

1. create a `thubConfig.yaml` file anywhere on your computer.
2. This file should contain the following:

```yaml
masterPassword: 'YOURPASSWORD'
accounts:
  - name: '[Any name you want]'
    serverUrl: '127.0.0.1:10009' # or whichever port where you are running the gRPC endpoint
    macaroonPath: '/path/to/admin.macaroon'
    certificatePath: '/path/to/tls.cert'
```
3. in the `.env` file in the `/thunderhub` folder you should add this line:
`ACCOUNT_CONFIG_PATH='/path/to/config/thubConfig.yaml'`
4. run the server. If everything was done correctly you see something like this in the logs:
`info [THUB]: Server accounts that will be available: Any name you want`

Unsure about the flash of the screen. Any error that appears?
